import { Inter } from "next/font/google";
import { Navbar } from "flowbite-react";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <div className="bg-cyan-700 p-4">
          <nav>
            <ul className="navbar gap-4 justify-center">
              <li className="text-2xl font-bold text-white">
                <Link href="/">Home</Link>
              </li>

              <li className="text-2xl font-bold text-white">
                <Link href="/createQuiz">Create Quiz</Link>
              </li>

              <li className="text-2xl font-bold text-white">
                <Link href="/viewQuizzes">View Quizzes</Link>
              </li>
            </ul>
          </nav>
        </div>

        {children}
      </body>
    </html>
  );
}
